version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: go_rotator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: migration
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./config.docker.json:/app/config.json:ro
    command: [ "/bin/app" ]

  rotator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: rotator
    depends_on:
      - migrations
    ports:
      - '8080:8080'
    volumes:
      - ./config.docker.json:/app/config.json:ro
    command: ["/bin/app", "--config=/app/config.json"]


volumes:
  pgdata: