version: '3.8'

services:


  rotator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: rotator
    ports:
      - '8080:8080'
    volumes:
      - ./config.docker.json:/app/config.json:ro
    command: ["/bin/app", "--config=/app/config.json"]
