name: FinalProject

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci.yml ./...

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
      - run: go mod download
      - run: go test -race -count=100 ./...

  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
      - run: go mod download
      - run: mkdir -p bin
      - run: go build -o bin/rotator ./cmd/rotator
      - uses: actions/upload-artifact@v4
        with:
          name: rotator-binary
          path: bin/rotator
